// This code calculate and plot the Pt broadening usins the histograms generated by Integration.cpp
// It can be compile with
// g++ -Wall -fPIC -I./include `root-config --cflags` Broadening.cpp -o ./bin/Broadening  `root-config --glibs` ./include/Broad.h

#include "Broad.h"

int main(){

  TStopwatch t;

  TString inputDirectory  = "/home/matias/proyecto/Pt2Broadening_multi-pion/Data/";
  TString plotDirectory   = "/home/matias/proyecto/Pt2Broadening_multi-pion/Plots/";

  PtBroadeningQ2Integrated(  inputDirectory, plotDirectory);
  PtBroadeningNuIntegrated(  inputDirectory, plotDirectory);
  PtBroadeningZhIntegrated(  inputDirectory, plotDirectory);
  PtBroadeningFullIntegrated(inputDirectory, plotDirectory);

  t.Print();

}
