// This code calculate and plot the Pt broadening using the histograms generated by Integration.cpp
// It can be compile with
// g++ -Wall -fPIC -I./include `root-config --cflags` Broadening.cpp -o ./bin/Broadening  `root-config --glibs` ./include/Broad.h

#include "Broad.h"

int main(){

  TStopwatch t;

  TString inputDirectory  = "/home/matias/proyecto/Pt2Broadening_multi-pion/Data/Nubins/";
  TString plotDirectory   = "/home/matias/proyecto/Pt2Broadening_multi-pion/Plots/nubins/";

  // PtBroadeningQ2Integrated(  inputDirectory, plotDirectory);
  // PtBroadeningNuIntegrated(  inputDirectory, plotDirectory);
  // PtBroadeningZhIntegrated(  inputDirectory, plotDirectory);
  // PtBroadeningFullIntegrated(inputDirectory, plotDirectory);

  PtbroadeningMultiZh(inputDirectory, plotDirectory);
  // char cQ2[3] = {'Q', '2', '\0'};
  // PtBroadeningVarIntegrated(cQ2, N_Q2, inputDirectory, plotDirectory);
  t.Print();

}
